### ISSUE TITLE
Not able to build dev image of elabftw on Windows 10

### ISSUE THREAD

**Issue by oli-ver** [elabftw/elabimg#1]
I tried to prepare my development environment to be able to contribute to elabftw.

When trying to build a dev image of elabftw I get several error messages.

Following the steps from the [contributing page](https://elabftw.readthedocs.io/en/latest/contributing.html#contributing-to-the-code) I geht the following error message:

`ln: failed to create symbolic link '/usr/bin/php': File exists`

Here is the complete logfile:

[try1_ln_fails.zip](https://github.com/elabftw/elabimg/files/981092/try1_ln_fails.zip)

I tried to delete the command `&& ln -s /usr/bin/php7 /usr/bin/php`.

After that I get the following error message:

`The requested PHP extension ext-gmagick * is missing from your system. Install or enable PHP's gmagick extension.`

Here is the complete logfile again:

[try2_php7_fails.zip](https://github.com/elabftw/elabimg/files/981094/try2_php7_fails.zip)

I tried to install the extension using the following commands:

```
RUN echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk upgrade -U -a && apk add --update \
[...]
php7-gmagick \
[...]
```

After that I get the error message:

`Installation request for onelogin/php-saml 2.10.5 -> satisfiable by onelogin/php-saml[2.10.5].`

I did not manage to get this dependency working. I am stuck at 

`onelogin/php-saml 2.10.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.`

I tried to install the packages php7-xml and php7-intl as suggested in some forums, but this did not work:
[try3_php-saml_fails.zip](https://github.com/elabftw/elabimg/files/981113/try3_php-saml_fails.zip)

Is there something I am missing?

Here is my last version of the Dockerfile:

[Dockerfile.zip](https://github.com/elabftw/elabimg/files/981114/Dockerfile.zip)

**Comment by NicolasCARPi** [comment]
Yes yes, I forgot to merge the hypernext branch into the dev branch of elabimg. I'll do that now. Done. Try again now with fresh dev branch.
