### ISSUE TITLE
JDK11 not available for arm/v7

### ISSUE THREAD

**Issue by din14970** [elabftw/elabimg#14]
My docker build of hypernext is failing for arm/v7 because apparently jdk11 has not been built as an alpine package for this architecture. Is jdk11 strictly necessary for recent changes in eLabFTW or will it also work with jdk8? i.e. can I work with a custom Dockerfile or will I have to dig into how to create an alpine package?

**Comment by NicolasCARPi** [comment]
Hello Neils,

The jdk stuff is only used for trusted timestamping, so not critical, you can do without it and I believe it'll work with jdk8.
