### ISSUE TITLE
Autobuilding of ARM images partially working + questions

### ISSUE THREAD

**Issue by din14970** [elabftw/elabimg#15]
Hi Nico, this is not a bug, I just wanted to inform you that my workflow for automatically building ARM 32/64 images for eLabFTW v 3.6.x with Github actions seems to be working. I will probably have to continuously update the scripts with new additions of dependencies which may not be compatible with the architecture. 

To test it, I installed v3.6.7 on my raspberry pi and so far it is running without any problem:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/25320842/119674439-7ed2ee00-be3c-11eb-98fb-2a0082af2ff8.png">

The github workflows are here:
https://github.com/din14970/elab-arm-docker

The resulting docker images here:
https://hub.docker.com/repository/docker/nielscautaerts/elabimg/tags?page=1&ordering=last_updated

There is a workflow `checkupdate.yml` which checks every day if there is a new version of eLabFTW. If so it updates the repo and launches the `make_latest_image.yml` build of that version for amd64, arm32 and arm64. To build 3.6.x, it still uses the old amd64 exclusive Docker file to ensure reproducible builds, so I just modify it with sed directly in the github action to fix the s6 issue.

In addition, I wanted to try and create a daily build of `hypernext` with `make_hypernext_image.yml`. Unfortunately, new dependencies have been introduced which are arm32 incompatible, like `openjdk11` and `cypress`. I tried some sed magic to edit these dependencies if arm32 is the target platform. The image builds, but unfortunately does not work (I get stuck in an error loop `nginx: [emerg] cannot load certificate "/etc/nginx/certs/server.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`)

Some questions:

* Do you know what might be breaking the hypernext image for arm32? Is there a workaround for cypress? If not I guess 3.6.7 will be the last version that will work on arm32.
* Would it be OK if I add a page to the eLabFTW docs to explain how to install on a raspberry pi? I think a lot of users who just want a personal eLabFTW instance in their house would find this helpful. On the other hand I would have to refer to my "unofficial" image which looks bad in the documentation.
* Do you think you could use this or could this be usefully integrated somehow? The way it is set up now is a very complicated way to build the images; much more convenient would be if the Dockerfile would be in the main eLabFTW repo and a new build for all platforms is triggered by github actions every time you create a release, push to a branch, or modify the docker file. But the implication would be that arm32 support is "official", and I understand you don't want to deal with that.

**Comment by NicolasCARPi** [comment]
Hello Niels,

> Is there a workaround for cypress?

Cypress is only used for dev, so it's fine to remove it. Removing openjdk effectively means disabling the trusted timestamping with the default TSA. So this should be made clear to whoever is using it.

>  The image builds, but unfortunately does not work 

Looks like an issue with the self generated certificate, you should have an error when it tries to do that (maybe not enough entropy?).

> Would it be OK if I add a page to the eLabFTW docs to explain how to install on a raspberry pi?

No. In the beginning I used to highly promote RPi installs, until I realized that filesystem corruption is a real problem on these devices and stopped recommending it. Also, as you have seen, ARM brings a few issues that I don't want to have to deal with (there are already enough complications like that! ;) ). eLabFTW being somewhat a professional software, this can be a big deal to some users who didn't backup properly (and backups might be corrupted, too!). So if RPi is mentionned in the doc it should only be to have this warning not to install it on.

> Do you think you could use this or could this be usefully integrated somehow?

I'm open to integrating it, yes, as ARM build might be useful for NAS devices.

> But the implication would be that arm32 support is "official", and I understand you don't want to deal with that.

Or we can have a clear disclaimer that it's a second-class citizen and users should use x64 arch. I would be fine with that.

As for the documentation, on the Install on NAS there could be a new section for ARM (which could also incidently be referred to for RPi, unofficially).
