### ISSUE TITLE
Allow Cross-Origin Request when calling the API using JS XMLhttprequest

### ISSUE THREAD

**Issue by moamer-dev** [elabftw/elabimg#29]
# Feature request

Hello,
Would you please allow the cross origin request on your server as I am trying to call an API using GET in JavaScript but I get (Method not allowed) with the following err (Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at .../api/v1/ex
periments/16?format=json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Thank you.

**Comment by NicolasCARPi** [comment]
Hello,

I've implemented that change. See https://github.com/elabftw/elabapi-javascript-example#readme for example code. Will work with 4.4.0-beta7.
