### ISSUE TITLE
Disabling SSL but still facing SSL issues

### ISSUE THREAD

**Issue by titansmc** [elabftw/elabimg#3]
Hi, I am running elabftw through Marathon (DC/OS) but after disabling SSL since I have SSL termination on the marathon-lb (proxy):
 
DISABLE_HTTPS = false

I see errors on the web browser randomly : 

![image](https://user-images.githubusercontent.com/8192096/42635765-37c99a08-85e7-11e8-8c3f-63a5eefd28e5.png)

**Comment by NicolasCARPi** [comment]
So you want to disable SSL but you put DISABLE_SSL = false ?? Try with true ;)

**Comment by titansmc** [comment]
Hahah sorry, I wanted to say "I have it set to true"

**Comment by NicolasCARPi** [comment]
And when you say "randomly" it means sometimes it work and sometimes not?

The elabftw docker will listen on the port of your chosing (443 internally) with an HTTP server. The ssl_error_rx_record_too_long is when you send an HTTPS request to an HTTP server, so the issue might be in your marathon configuration not terminating the SSL properly every time imho. I'm not familiar at all with Marathon. Do you have several containers for load balancing? This might explain the "random" part.

**Comment by titansmc** [comment]
Sorry, I think I have the issue somewhere else in the load balancer level, it looks to me.... I apologize for the error.

**Comment by NicolasCARPi** [comment]
Ok no prob :)
