### ISSUE TITLE
Line 129 running into errors while being executed in WSL 

### ISSUE THREAD

**Issue by rinky97** [elabftw/elabimg#36]
https://github.com/elabftw/elabimg/blob/23f1a4f8d28279cac47ead4ad6a631009f03de8d/Dockerfile#L129

~~~
 => ERROR [cronie-builder 7/7] RUN abuild-keygen -n -a && abuild && find /home/builder/packages -type f -name 'cr  3.0s
 => [nginx-builder  5/16] WORKDIR /build                                                                           0.1s
 => [nginx-builder  6/16] RUN git clone https://github.com/google/ngx_brotli && cd ngx_brotli && git reset --hard  1.9s
 => CANCELED [nginx-builder  7/16] RUN git clone --depth 1 -b v0.34 https://github.com/openresty/headers-more-ngi  0.8s
------
 > [cronie-builder 7/7] RUN abuild-keygen -n -a && abuild && find /home/builder/packages -type f -name 'cronie-1*.apk' -exec mv {} /build/apk ;:
#0 2.974 writing RSA key
#0 2.975 >>>
#0 2.975 >>> You'll need to install /home/builder/.abuild/-65148914.rsa.pub into
#0 2.975 >>> /etc/apk/keys to be able to install packages and repositories signed with
#0 2.975 >>> /home/builder/.abuild/-65148914.rsa
#0 2.975 >>>
#0 2.975 >>> Please remember to make a safe backup of your private key:
#0 2.975 >>> /home/builder/.abuild/-65148914.rsa
#0 2.975 >>>
: not foundsr/bin/abuild: /build/APKBUILD: line 17:
------
Dockerfile:129
--------------------
 127 |     # we move it to /build so it's easier to find from the other image
 128 |     # use cronie-1 to avoid copying cronie-doc
 129 | >>> RUN abuild-keygen -n -a && abuild && find /home/builder/packages -type f -name 'cronie-1*.apk' -exec mv {} /build/apk \;
 130 |     # END CRONIE BUILDER
 131 |
--------------------
ERROR: failed to solve: process "/bin/sh -c abuild-keygen -n -a && abuild && find /home/builder/packages -type f -name 'cronie-1*.apk' -exec mv {} /build/apk \\;" did not complete successfully: exit code: 127
~~~

Any suggestions are appreciated

**Comment by NicolasCARPi** [comment]
Hello,

Unfortunately, I have no idea where the issue is coming from. And no plan to try and debug anything related to Windows. Can't you build it on a proper GNU/Linux system. Why do you build it yourself in the first place if I may ask?

**Comment by rinky97** [comment]
well it is a prototype I am testing out internally before it's deployed on Jenkins, might I ask if there are alternative packages that be referenced to do the same thing as this line.. or what exactly is it that this line is trying to do that I can modify to test by myself.

**Comment by NicolasCARPi** [comment]
Well the error is a bit weird: `: not foundsr/bin/abuild: /build/APKBUILD: line 17:`

Line 17 of the APKBUILD is blank :/

Can it be that your server cannot reach github?

**Comment by rinky97** [comment]
I cloned this repository into my local and have been running it from there, is there some way I can verify if the server is able to connect to Git Hub? 
My understanding is that the docker file specifies everything that needs to be part of the container that ELN lives on and is not really dependent on what host OS I have, so in theory it shouldn't matter where I run this I believe.

**Comment by NicolasCARPi** [comment]
> so in theory it shouldn't matter where I run this I believe.

Depends on your network rules. At some point it fetches cronie source from github, and it seems this is the step that fails.

> is there some way I can verify if the server is able to connect to Git Hub?

Of course. Try to GET this from your server: 

~~~bash
curl https://github.com/cronie-crond/cronie/releases/download/cronie-1.5.7/cronie-1.5.7.tar.gz || echo "FAIL"
~~~

You can also comment out this step and see if it blocks later when it tries again to get elabftw source from github.

**Comment by rinky97** [comment]
thanks , this is what I get - 
curl https://github.com/cronie-crond/cronie/releases/download/cronie-1.5.7/cronie-1.5.7.tar.gz -o output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by NicolasCARPi** [comment]
> Looks like it is getting connected but not fetching any data

Indeed, sorry I cannot be of more help, but this issue is on your end.
