### ISSUE TITLE
Open_basedir /.dockerenv problem

### ISSUE THREAD

**Issue by oli-ver** [elabftw/elabimg#5]
When trying to get my dev environment up and running again an error occured when running `docker exec -it elabftw composer install`:
```
[ErrorException]                                                                                                                            
  file_exists(): open_basedir restriction in effect. File(/.dockerenv) is not within the allowed path(s): (/elabftw/:/tmp/:/root/.composer:/  
  usr/bin/composer:/usr/bin/unzip)    
```
Adding `/.dockerenv` to the open_basedir path in php.ini seems to fix it.

**Comment by NicolasCARPi** [comment]
Yes I realized that too some time ago, I used another approach:

https://github.com/elabftw/elabimg/commit/1458d7b

Did you use this version (meaning this fix didn't work)?

**Comment by oli-ver** [comment]
I pulled elabftw/elabimg:latest which is 4 weeks old. Has you fix been published yet? As it is part of the master branch and tagged with a version I would assume so, right?

**Comment by NicolasCARPi** [comment]
I think if you build it yourself you'll get the fix but the one from docker hub might not have it.

**Comment by oli-ver** [comment]
I just built the dev branch myself and are still reproducing the issue:
```
 [ErrorException]                                                                                                                                                       
  file_exists(): open_basedir restriction in effect. File(/.dockerenv) is not within the allowed path(s): (/elabftw/:/tmp/:/root/.composer:/usr/bin/composer:/usr/bin/u  
  nzip)  
```

I checked the commit history: Your fix has been merged to the dev branch but seems not to work (perhaps .dockerenv is being created during another step?). When testing with a docker image with the fixed open_basedir path it's working.

**Comment by NicolasCARPi** [comment]
Ok I'll merge your change then. You can even add a commit on your PR to remove the rm .dockerenv from the Dockerfile ;)

**Comment by oli-ver** [comment]
@NicolasCARPi Sure, I updated the branch with your suggestion

**Comment by oli-ver** [comment]
@NicolasCARPi Sorry, I got confused with the branches. My commit was not on the patch-2 branch but on the dev branch in my fork. Is it possible that my pull request needs to be set to the dev branch, too? Right now it's for hypernext. I will push the change to the patch-2 branch now.
